In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

## Đọc dữ liệu

In [13]:
df = pd.read_csv('data.csv',delimiter=',')

X = df.drop('class', axis=1)
X=(X-X.min())/(X.max()-X.min()) #Chuẩn hoá dữ liệu
y = df['class']
X=X.values
y=y.values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

## Các giải thuật

### Bayes

In [14]:
#Huấn luyện mô hình
nb = GaussianNB()
nb.fit(X_train, y_train)

#Ma trận nhầm lẫn
thucte= y_test
dubao= nb.predict(X_test)
mtx=confusion_matrix(thucte,dubao)
print(mtx)

#Độ chính xác mô hình
y_pred_nb = nb.predict(X_test)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Độ chính xác thuật toán Bayes:", accuracy_nb)

[[3354  311]
 [1310  731]]
Độ chính xác thuật toán Bayes: 0.715913073957238


### Cây quyết định

In [15]:
# Xây dựng mô hình Decision Tree và huấn luyện trên tập huấn luyện
clf = DecisionTreeClassifier(random_state=5)
clf.fit(X_train, y_train)

#Ma trận nhầm lẫn
thucte= y_test
dubao= clf.predict(X_test)
mtx=confusion_matrix(thucte,dubao)
print(mtx)

# Đánh giá mô hình trên tập kiểm tra
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Độ chính xác cây quyết định:", accuracy)

[[3139  526]
 [ 512 1529]]
Độ chính xác cây quyết định: 0.8180862250262881


### Rừng ngẫu nhiên

In [16]:
# Huấn luyện mô hình rừng ngẫu nhiên
rf = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=0)
rf.fit(X_train, y_train)

thucte= y_test
dubao= rf.predict(X_test)
mtx=confusion_matrix(thucte,dubao)
print(mtx)

y_pred_rf = rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Độ chính xác thuật toán rừng ngẫu nhiên:", accuracy_rf)

[[3441  224]
 [ 519 1522]]
Độ chính xác thuật toán rừng ngẫu nhiên: 0.8697861899754644
